AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template using AWS Certificate Manager (ACM) with Automated Route 53 DNS Validation"

Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "staging.timjosmith.com"
      DomainValidationOptions:
        - DomainName: "staging.timjosmith.com"
          HostedZoneId: Z07023503P1PJJX3TKC0  # ✅ Ensure correct Hosted Zone ID
      ValidationMethod: DNS


