AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Staging S3, SSL Certificate, Route 53, and CloudFront

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: resume.staging.com
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: Staging


