name: Deploy CloudFormation Stack to Main Branch

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Enables OpenID Connect (OIDC) authentication
      contents: read

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials (Using OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline  # ✅ Replace with your IAM role ARN
          aws-region: eu-west-2  # ✅ Ensure the correct region is used

      # Step 3: Check If Stack Exists
      - name: Check If Stack Exists
        id: check_stack
        run: |
          echo "🔍 Checking if CloudFormation stack exists..."
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name staging-cloudfront-stack --region eu-west-2 --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "DOES_NOT_EXIST")
          echo "STACK_STATUS=$STACK_STATUS" >> $GITHUB_ENV
          echo "✅ Stack Status: $STACK_STATUS"

      # Step 4: Validate CloudFormation Template
      - name: Validate CloudFormation Template
        run: |
          echo "🔍 Validating CloudFormation template..."
          aws cloudformation validate-template --template-body file://main.yml
          echo "✅ Template validation passed."

      # Step 5: Create or Update CloudFormation Stack
      - name: Create or Update CloudFormation Stack
        run: |
          if [[ "$STACK_STATUS" == "DOES_NOT_EXIST" ]]; then
            echo "🚀 Stack does not exist. Creating a new CloudFormation stack..."
            aws cloudformation create-stack \
              --stack-name staging-cloudfront-stack \
              --template-body file://main.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --region eu-west-2

            echo "⏳ Waiting for stack creation to complete..."
            aws cloudformation wait stack-create-complete --stack-name staging-cloudfront-stack --region eu-west-2
            echo "✅ Stack created successfully."
          else
            echo "✅ Stack already exists. Updating stack..."
            aws cloudformation deploy \
              --stack-name staging-cloudfront-stack \
              --template-file main.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --region eu-west-2 \
              --no-fail-on-empty-changeset
            echo "✅ Stack updated successfully."
          fi
