name: Deploy CloudFormation Stack to Main Branch

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Enables OpenID Connect (OIDC) authentication
      contents: read

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials (Using OIDC or Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline  # Replace with your IAM role ARN
          aws-region: eu-west-2  # Adjust to your AWS region

      # Step 3: Validate CloudFormation template
      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://main.yml

      # Step 4: Deploy CloudFormation stack to staging
      - name: Deploy CloudFormation Stack (Staging)
        run: |
          aws cloudformation deploy \
            --stack-name staging-cloudfront-stack \
            --template-file cloudformation.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides DomainName=resume.staging.com

